"""
nodes/kv_sandbox.py - KV extraction sandbox.

Runs code generated by kv_codegen_node. This is intentionally separate from the
table sandbox because KV code returns a flat dict and uses extract(ws,
merged_map, bboxes).
"""

import builtins
import json
import math
import re
import traceback
from typing import Any, Dict

import openpyxl

from excel_agent.state import AgentState


_SAFE_BUILTINS = {
    name: getattr(builtins, name)
    for name in [
        "int", "float", "str", "bool", "list", "dict", "tuple", "set",
        "bytes", "bytearray", "type", "object",
        "len", "range", "enumerate", "zip", "map", "filter", "sorted",
        "reversed", "sum", "min", "max", "abs", "round", "divmod", "pow",
        "print", "repr", "format", "chr", "ord",
        "isinstance", "issubclass", "hasattr", "getattr", "setattr",
        "callable", "iter", "next", "all", "any",
        "Exception", "ValueError", "TypeError", "KeyError", "IndexError",
        "StopIteration", "RuntimeError",
        "True", "False", "None",
    ]
    if hasattr(builtins, name)
}


def _find_sheet(wb, requested: str) -> str:
    if requested in wb.sheetnames:
        return requested
    req = (requested or "").strip().upper()
    for name in wb.sheetnames:
        if name.strip().upper() == req:
            return name
    return requested


def _latest_code(state: AgentState) -> str:
    kv_state = state.get("kv_state", {}) or {}
    code = kv_state.get("generated_code")

    cache = kv_state.get("cache") or {}
    if cache.get("cache_hit") and cache.get("code"):
        return cache["code"]

    if isinstance(code, list):
        return code[-1] if code else ""
    return code or ""


def _build_merge_map(ws) -> Dict[tuple, Dict[str, Any]]:
    merged_map: Dict[tuple, Dict[str, Any]] = {}
    for rng in ws.merged_cells.ranges:
        value = ws.cell(row=rng.min_row, column=rng.min_col).value
        info = {
            "min_row": rng.min_row,
            "max_row": rng.max_row,
            "min_col": rng.min_col,
            "max_col": rng.max_col,
            "value": value,
        }
        for r in range(rng.min_row, rng.max_row + 1):
            for c in range(rng.min_col, rng.max_col + 1):
                merged_map[(r, c)] = info
    return merged_map


def _run_with_timeout(fn, timeout_sec: int = 30):
    try:
        import signal

        def _handler(signum, frame):
            raise TimeoutError(f"代码执行超时（>{timeout_sec}s）")

        old = signal.signal(signal.SIGALRM, _handler)
        signal.alarm(timeout_sec)
        try:
            return fn()
        finally:
            signal.alarm(0)
            signal.signal(signal.SIGALRM, old)
    except (ImportError, AttributeError):
        return fn()


def _fmt(v: Any) -> str:
    if v is None:
        return ""
    if isinstance(v, float) and v == int(v):
        return str(int(v))
    return str(v).strip()


def _validate_result(raw: Any, kv_list: list) -> Dict[str, str]:
    if not isinstance(raw, dict):
        raise ValueError(f"extract() 必须返回 dict，实际返回 {type(raw).__name__}")

    result: Dict[str, str] = {}
    for key in kv_list:
        result[str(key)] = _fmt(raw.get(key, ""))

    for key, value in raw.items():
        if key not in result:
            result[str(key)] = _fmt(value)

    return result


def kv_sandbox_node(state: AgentState) -> dict:
    config = state.get("config", {}) or {}
    kv_list = config.get("kv_list") or config.get("subtable_titles") or []
    code = _latest_code(state)

    if not code:
        return {"sandbox_error": "KV generated_code 为空。"}

    excel_path = config.get("excel_path")
    sheet_name_req = config.get("sheet_name")

    try:
        wb = openpyxl.load_workbook(excel_path, data_only=True)
        sheet_name = _find_sheet(wb, sheet_name_req)
        if sheet_name not in wb.sheetnames:
            return {"sandbox_error": f"无法找到 Sheet：{sheet_name_req}"}
        ws = wb[sheet_name]
    except Exception as e:
        return {"sandbox_error": f"无法打开 Excel 文件：{e}"}

    kv_state = state.get("kv_state", {}) or {}
    sheet_structure = kv_state.get("sheet_structure", {}) or {}
    bboxes = sheet_structure.get("bboxes", {}) or {}
    merged_map = _build_merge_map(ws)

    namespace = {
        "__builtins__": _SAFE_BUILTINS,
        "re": re,
        "math": math,
        "json": json,
        "kv_configs": kv_list,
        "sheet_structure": sheet_structure,
    }

    try:
        exec(compile(code, "<kv_llm_generated>", "exec"), namespace)
    except Exception:
        return {
            "sandbox_error": f"KV 代码编译/定义阶段报错：\n{traceback.format_exc()}",
        }

    extract_fn = namespace.get("extract")
    if not callable(extract_fn):
        return {"sandbox_error": "KV 代码中未找到 extract 函数。"}

    try:
        raw = _run_with_timeout(lambda: extract_fn(ws, merged_map, bboxes))
        result = _validate_result(raw, kv_list)
        return {
            "kv_state": {"extracted_data": result},
            "raw_result": result,
            "result": result,
            "final_output": result,
            "sandbox_error": None,
        }
    except TimeoutError as e:
        return {"sandbox_error": str(e)}
    except Exception:
        return {
            "sandbox_error": f"KV extract() 执行时报错：\n{traceback.format_exc()}",
        }
