excel_path: "./ws_test_file_use.xlsx"
sheet_name: "WL_56A0DS6"
subtable_title: "Group 1 Wireless Antenna, Group 2 Wireless Antenna, Group 3 Wireless Antenna"
target_columns:
  - parent: null
    child: "Sector 1"
  - parent: null
    child: "Sector 2"
  - parent: null
    child: "Sector 3"