excel_path: "./ws_test_file_use.xlsx"
sheet_name: "CONFIGURATION"
subtable_titles:
  - "2G Configuration"
  - "3G Configuration"
  - "4G Configuration"
  - "5G Configuration"

subtable_configs:
  "2G Configuration":
    col_headers:
      - "SYSTEM MODULE"
      - "CELL"
      - "RF MODULE||TYPE"
      - "RF MODULE||QTY."
      - "ANTENNAS||NEW/SWAP/EXIST"
      - "ANTENNAS||Antenna Type"

  "3G Configuration":
    col_headers:
      - "SYSTEM MODULE"
      - "CELL"
      - "RF MODULE||TYPE"
      - "RF MODULE||QTY."
      - "ANTENNAS||NEW/SWAP/EXIST"
      - "ANTENNAS||Antenna Type"

  "4G Configuration":
    col_headers:
      - "RF MODULE||QTY."
      - "ANTENNAS||NEW/SWAP/EXIST"
      - "ANTENNAS||Antenna Type"

  "5G Configuration":
    col_headers:
      - "SYSTEM MODULE"
      - "CELL"
      - "RF MODULE||TYPE"